name: sri_kumaran_engineering_works
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: ^3.6.0
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.0.3
  fluttertoast: ^8.2.10
  firebase_messaging: 
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  flutter_local_notifications: ^17.2.1+1
  audioplayers: ^6.1.0
  path_provider: ^2.1.1
  permission_handler:
  pdf: ^3.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_logo/skew_logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_logo/
    - assets/fonts/

  fonts:
    - family: "Comfortaa"
      fonts:
        - asset: "assets/fonts/Comfortaa-700.ttf"
          style: "normal"
          weight: 700
